### ISSUE TITLE
When trying to compile, I get a String error

### ISSUE THREAD

**Issue by felix91gr** [yonaskolb/Beak#22]
I'm on Linux, under Swift 4.1

This is what I ran:

```console
felix@felix-X550LD ~/D/P/A/beak> swift build
Compile Swift Module 'BeakCore' (15 sources)
/home/felix/Documents/Programming/AwesomeSystemSwift/beak/Sources/BeakCore/SourceKit.swift:86:54: error: value of type 'String' has no member 'substringWithByteRange'
        let substring = range(for: source).flatMap { contents.substringWithByteRange(start: Int($0.offset), length: Int($0.length)) }
                                                     ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
error: terminated(1): /home/felix/Documents/Programming/Binaries/swift/swift-4.1-snapshot/usr/bin/swift-build-tool -f /home/felix/Documents/Programming/AwesomeSystemSwift/beak/.build/debug.yaml main output:
    

```

[This line](https://github.com/yonaskolb/Beak/blob/f8431845a9844a7a736a5e369025420a5edf0aef/Sources/BeakCore/SourceKit.swift#L86)'s the one causing the error. Maybe the library hasn't been updated to Swift 4.1?

Anyway. Thanks for your help, and I hope you have a good day :)

**Comment by yonaskolb** [comment]
Hi @felix91gr 
Did it work before in Swift 4.0 on Linux?
It works on Swift 4.1 on macOS. Beak hasn't actually been tested on Linux, but it's something that can be looked at

**Comment by felix91gr** [comment]
> Beak hasn't actually been tested on Linux, but it's something that can be looked at

Ohh! You can try to do it in a sandbox with Docker. Benedikt Terhechte [did that for SourceKittenDaemon](https://github.com/terhechte/SourceKittenDaemon#linux) so that Mac users can run the tests locally for Linux as well. The setup is super easy :)

> Did it work before in Swift 4.0 on Linux?

Haven't tried. I'm gonna see if I still have the 4.0 toolchain somewhere. If not, I'll download another one and test it. Maybe the 4.0 -> 4.1 transition broke it somehow.

**Comment by felix91gr** [comment]
Yup, it doesn't work under 4.0 either. I'm gonna investigate further.

**Comment by yonaskolb** [comment]
Thanks @felix91gr

**Comment by felix91gr** [comment]
Hmm. Is `substringWithByteRange` a property provided by `Foundation`? Since `Foundation` is incomplete on Linux, maybe therein lies the problem :thinking:

**Comment by felix91gr** [comment]
It's [provided by `SourceKittenFramework`](https://github.com/paulyoung/sourcekitten/blob/02484b993821d8a1ba000bda28568033db94adbe/Source/SourceKittenFramework/String%2BSourceKitten.swift#L130)! Jesus, I never would've guessed. Of course I'd have a hard time looking it up in Apple's documentation :laughing: 

Now then... why does the compiler fail to see it in Linux? :thinking: this is gonna need some digging around.

**Comment by yonaskolb** [comment]
Any updates on this @felix91gr?

**Comment by felix91gr** [comment]
No! I'm sorry, I've been away at other projects and studying. I will put it on my to-do list to debug this someday :) (maybe in July, when I have winter holidays)

In the meantime, you can try to run the tests in Linux with a more polished docker utility: [this one which is new and really and nice](https://github.com/iainsmith/swift-docker).

Again, sorry for disappearing. I must've closed the tab I had Beak on, and then it slipped through my fingers 😅

**Comment by yonaskolb** [comment]
All good! Got swift-docker up and running now, it's great!

**Comment by yonaskolb** [comment]
Fixed here #33
